drop table if exists Product;

create table if not exists Product(
    id bigint generated by default as identity primary key,
    name varchar(256) not null,
    price int not null
);

create table if not exists "user"(
     id bigint generated by default as identity primary key,
     login varchar(256) not null,
     password varchar(256) not null,
     status_authentication boolean not null
);